create table if not exists public.ops_events (
  id bigint generated by default as identity primary key,
  source text not null,
  event_type text not null check (event_type in ('log', 'heartbeat', 'weekly_report')),
  level text not null check (level in ('debug', 'info', 'warn', 'error')),
  message text not null,
  payload jsonb not null default '{}'::jsonb,
  happened_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.ops_events enable row level security;

create policy "service_role can manage ops_events"
  on public.ops_events
  for all
  to service_role
  using (true)
  with check (true);

revoke all on table public.ops_events from anon, authenticated;
grant select, insert, update, delete on table public.ops_events to service_role;

create index if not exists ops_events_created_at_idx on public.ops_events (created_at desc);
create index if not exists ops_events_event_type_created_at_idx on public.ops_events (event_type, created_at desc);
create index if not exists ops_events_source_created_at_idx on public.ops_events (source, created_at desc);

revoke execute on function public.rls_auto_enable() from public, anon, authenticated;
